#!/bin/bash

cd "/Applications/mBRCTool.app/"

# process origin binary
mv mBRCTool mBRCTool_
chown root.wheel mBRCTool_
chmod +s 		 mBRCTool_

cont=`cat <<"EOF"
#!/bin/bash
dir=$(dirname "$0")
exec "${dir}"/mBRCTool_ "$@"
EOF
`
# create new fake binary
echo -e "$cont" > mBRCTool
chown root.wheel  mBRCTool
chmod +x 		  mBRCTool
